import { type Metadata } from "next";
import { inter } from "@/app/fonts";
import "./globals.css";
import ReduxProvider from "./Providers/ReduxProvider";
import Header from "./components/Header/Header.component";
import Footer from "./components/Footer/Footer.component";
import GoogleMapProvider from "./Providers/GoogleMapProvider";
import CaptchaProvider from "./Providers/CaptchaProvider";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body className={`${inter.className} min-h-screen bg-primary`}>
        <ReduxProvider>
          <GoogleMapProvider>
            <CaptchaProvider>
              <Header />
              <main className="xl:mt-16 mt-[100px] xl:px-1 px-8 overflow-x-clip bg-transparent">
                {children}
                <SpeedInsights />
              </main>
              <Footer />
            </CaptchaProvider>
          </GoogleMapProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
