import { type Metadata } from "next";
import { inter } from '@/app/fonts'
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import Header from "./components/Header/Header.component";
import Footer from "./components/Footer/Footer.component";
import GoogleMapProvider from "./GoogleMapProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW">
      <body className={`${inter.className} bg-theme-light min-h-screen`}>
        <ReduxProvider>
          <GoogleMapProvider>
            <Header />
            <main className="relative bg-transparent 
          xl:px-1 px-8
          overflow-x-clip
          xl:mt-16 mt-[100px]
          ">
              {children}
            </main>
            <Footer />
          </GoogleMapProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}


